### ISSUE TITLE
Sometimes you can't see/hear someones notes and/or lines

### ISSUE THREAD

**Issue by ghost** [nagalun/multiplayerpiano-server#1]
(regarding ourworldofpixels.com/piano) There is this annoying issue that is too common, where sometimes you cannot hear a certain person's notes and/or lines (but they can see yours). If either they or you reload one or more times it usually fixes it. World of Pixels Piano is awesome except for this annoying glitch that makes it troublesome to use.

**Comment by nagalun** [comment]
I didn't even notice until recently the server was getting so much traffic, I'll look into it.

**Comment by nagalun** [comment]
I think it shouldn't happen again, but tell me if it does

**Comment by ghost** [comment]
Just noticed it happening again; friend didn't see my notes even tho I could see his; we tried reloading and stuff but he never could get my notes.
