### ISSUE TITLE
limits notes and chat

### ISSUE THREAD

**Issue by danilqweasd12321** [nagalun/multiplayerpiano-server#17]
how to limit notes and chat?

**Comment by nagalun** [comment]
only chat limit is implemented, and the limits are defined here:
https://github.com/nagalun/multiplayerpiano-server/blob/master/src/limiter.hpp#L28

**Comment by danilqweasd12321** [comment]
a notes?

**Comment by nagalun** [comment]
note limit *is not* implemented

**Comment by danilqweasd12321** [comment]
ok i'll wait while you implement

**Comment by nagalun** [comment]
nah i won't implement it sorry, i don't need to limit notes. you can make a fork of this repo and do it though
