### ISSUE TITLE
How to start the server?

### ISSUE THREAD

**Issue by ghost** [nagalun/multiplayerpiano-server#2]
Can anyone help me?

**Comment by nagalun** [comment]
Have you compiled the server successfully?
If you have, just start it with the following parameters:
./server the_admin_password port
for example: ./server secretpass 1234
If you didn't compile yet the server, you need to download the sources, install the dependencies (zlib, openssl, libuv), enter the sources directory, and run 'make'

**Comment by ghost** [comment]
Ok, thanks :)
