### ISSUE TITLE
how do you compile this into a .exe?

### ISSUE THREAD

**Issue by ar06x** [nagalun/multiplayerpiano-server#23]
i would like to compile this into a single .exe file, but im not sure how this is compiled. felt like asking instead of spending hours trying to compile it into a .exe without knowing the proper way to compile this

**Comment by nagalun** [comment]
I used msys2 on windows, with all deps installed and the mingw compiler.
Not all libs play nice being statically compiled so I'd copy the .dlls that it needs from your pc if you need to run it somewhere else

**Comment by ar06x** [comment]
Ah, thanks. Also ty for quick response
