### ISSUE TITLE
Problems with ZLIB

### ISSUE THREAD

**Issue by Cronical2000** [nagalun/multiplayerpiano-server#3]
Hey, thanks for the repository.
Still not able to compile it becuase of ZLIB. Do you have a compiled one for Windows?
I would try to run it locally to playing with a friend together and hope it will be with much less delay.
Im not very good at cpp.
Thanks in forward.

**Comment by nagalun** [comment]
The multiplayerpiano client adds artificial delay to the notes, so even if run locally it may still have a delay.
I also never tried to compile this server for windows, so it may not work there without some work.
What compiler are you using?

**Comment by nagalun** [comment]
You can download the windows binary from here now btw:
https://github.com/nagalun/multiplayerpiano-server/releases
