### ISSUE TITLE
Empty sendArray causes server crash.

### ISSUE THREAD

**Issue by ar06x** [nagalun/multiplayerpiano-server#30]
```js
MPP.client.sendArray([""]);
```
Sending this can easily crash the server.

**Comment by ghost** [comment]
that's not empty but an array with an empty string. what about other strings, or other types like numbers, booleans and null? normally the array only ever has objects so perhaps the server doesn't expect other data types.

**Comment by nagalun** [comment]
https://github.com/nagalun/multiplayerpiano-server/blob/02c2e9916ee5251ec80ba8d8486b255d8f5710c0/src/server.cpp#L534
needs m.is_object() check and a try catch around it to ignore future slip-ups like these

**Comment by ghost** [comment]
fixed?

**Comment by ar06x** [comment]
> fixed?

Appears to be (In your server at least)

**Comment by nagalun** [comment]
On this one too, now.
