### ISSUE TITLE
Everyone Joining as 1 user.

### ISSUE THREAD

**Issue by Rem0n** [nagalun/multiplayerpiano-server#32]
Hello! I'm using bash on replit.com to host this and everyone is joining as one user.
Here's the code I'm using:
`cd /tmp
if test ! -d multiplayerpiano-server
then git clone https://github.com/nagalun/multiplayerpiano-server --recurse-submodules
fi
cd multiplayerpiano-server
make
cd /home/runner
/tmp/multiplayerpiano-server/out Password 1234 7D6400`
![image](https://user-images.githubusercontent.com/69490592/123751399-0eb3fe00-d8fb-11eb-9ef0-e86792e64b2a.png)
There are 3 people on my MPP clone, and everyone Joining as 1 user (me). I'm using a fork of [https://mpp.terrium.net/](url) if you need that infomation.

**Comment by Rem0n** [comment]
Github made my script into 1 line. here's a fix.

cd /tmp
if test ! -d multiplayerpiano-server
then git clone https://github.com/nagalun/multiplayerpiano-server --recurse-submodules
fi
cd multiplayerpiano-server
make
cd /home/runner
/tmp/multiplayerpiano-server/out Password 1234 7D6400

**Comment by ledlamp** [comment]
source code needs to be modified to get the user's address in x-forwarded-for. note that repl.it doesn't include the user's ip address if connected with tls for some reason.

If program is compiled with unix sockets patch, it will use x-real-ip header. This is designed for use behind nginx.

**Comment by Rem0n** [comment]
how can i do that?

**Comment by Rem0n** [comment]
do i just do
![image](https://user-images.githubusercontent.com/69490592/123943245-4eecac80-d9df-11eb-9f40-b2cd31ca7680.png)

**Comment by nagalun** [comment]
Replace that function with this one https://github.com/nagalun/multiplayerpiano-server/issues/27#issuecomment-741176261

**Comment by Rem0n** [comment]
okay

**Comment by Rem0n** [comment]
Thanks, Fixed it.
