### ISSUE TITLE
How to make the server public

### ISSUE THREAD

**Issue by Rem0n** [nagalun/multiplayerpiano-server#33]
I'm using the exe file that was compiled and can run it to localhost.
If I want other people to join, what do I do? 
I tried to put the IP in the port section like,
./server password ###.###.1.9:1234
and used the local IP address.

**Comment by nagalun** [comment]
There is no need to specify the IP, the default is to listen on all networks. Just specify the password and optionally the port.
You'll need to open the port you use in your router's config (look up tutorials on how to do that), or use some virtual private lan thing like hamachi or zerotier (less convenient for others).

**Comment by Rem0n** [comment]
so like port forward?

**Comment by Rem0n** [comment]
never mind.
