### ISSUE TITLE
MPP server not port forwarding on Microsoft Azure

### ISSUE THREAD

**Issue by rlem0n** [nagalun/multiplayerpiano-server#36]
I am using a Azure account (student acc) just temp, while I try to fix linode) and after compilation, it says the server is up, like normal
![image](https://user-images.githubusercontent.com/89490145/131232977-21aed663-7e06-4377-89f4-265b18b3908e.png)
but when I try to connect using
```
MPP.client.uri = "ws://20.85.232.79:1234";
MPP.client.ws.close();
```
and
```
MPP.client.uri = "wss://20.85.232.79:1234";
MPP.client.ws.close();
```
On [MPPT](https://mpp.terrium.net/), it won't connect.

It's probably an inbound/outbound rule, but I'm probably making a mistake or something?

btw here is how you add a rule.
![image](https://user-images.githubusercontent.com/89490145/131233013-179befd0-6f0b-471a-be3c-93d3788e1fa8.png)

**Comment by rlem0n** [comment]
oops, i ment:
```
MPP.client.uri = "ws://20.85.232.79:1234";
MPP.client.ws.close();
```

**Comment by rlem0n** [comment]
update 2, it says its open but still cant connect

**Comment by nagalun** [comment]
I mean, sorry for not replying, but I don't think this is a problem with this server in specific, exposing the port may not work for this or for any other service... You could try using another port on the mpp server like 8085, maybe 1234 is blocked on azure. But other than that I don't think I have anything to fix really.
