### ISSUE TITLE
Hey! 

### ISSUE THREAD

**Issue by ghost** [nagalun/multiplayerpiano-server#37]
I was trying to make a copy of this but the arrow files how did you make them?

**Comment by nagalun** [comment]
What are arrow files?

**Comment by ghost** [comment]
The file json @ 1126c9c and
uWebSockets @ c7aa984

**Comment by ghost** [comment]
those are git submodules, use --recursive with git clone

**Comment by ghost** [comment]
So how do I do it

**Comment by ghost** [comment]
use git submodule command to make them

**Comment by ghost** [comment]
# How 
No like how do I use the command?

**Comment by nagalun** [comment]
`git submodule add REPO_URL`

Either way you can probably find a nice tutorial on google on how to add submodules

**Comment by ghost** [comment]
Thanks

**Comment by ghost** [comment]
I am professional make me collab look:
![89A6EA43-DE79-447A-B587-D1644DA37653](https://user-images.githubusercontent.com/75795429/142785585-8f382cb5-ed87-4a9c-a89b-1e00dc61c4d6.jpeg)
