### ISSUE TITLE
Client?

### ISSUE THREAD

**Issue by lithiumjs** [nagalun/multiplayerpiano-server#4]
Alright, I have downloaded, compiled and started the server. How do I connect to it?

**Comment by nagalun** [comment]
You can use the official client's API to connect:
```
MPP.client.uri = "ws://localhost:1234";
MPP.client.ws.close();
```

**Comment by lithiumjs** [comment]
But what if I want to host the client publicly?

**Comment by nagalun** [comment]
Then you need to copy the client, and host those files using a separate http server.
Here's a recent client from MPP: http://ourworldofpixels.com/piano/mpp-client-2017-12-03.zip

If you are not hosting the piano server on the same address as the http server, or need to change the default port (8080), change it at script.js (line 1.100)

**Comment by lithiumjs** [comment]
Thanks! Also, what do I use the password for?

**Comment by nagalun** [comment]
The only use it has is to change a user's color with it, like this:
```
MPP.client.sendArray([{m: "adminmsg", password: "password_here", message: {m: "color", id: "user's id (not _id)", color: "#hexcolor"}}]);
```

**Comment by ghost** [comment]
> http://ourworldofpixels.com/piano/mpp-client-2017-12-03.zip

https://piano.ourworldofpixels.com/mpp-client-2017-12-03.zip
