### ISSUE TITLE
how to compile?

### ISSUE THREAD

**Issue by felpcereti** [nagalun/multiplayerpiano-server#8]

**Comment by nagalun** [comment]
Install dependencies, and execute `make` on the project root
Or if you don't want to compile use the already-compiled binaries: https://github.com/nagalun/multiplayerpiano-server/releases

**Comment by felpcereti** [comment]
but on windows how to "make"

**Comment by nagalun** [comment]
cygwin/msys2

**Comment by ghost** [comment]
fyi
```sh
git clone --recurse-submodules https://github.com/nagalun/multiplayerpiano-server.git
cd multiplayerpiano-server
make
./out password 1234
```
